### ISSUE TITLE
WebDriver spec needs to include the /shutdown endpoint

### ISSUE THREAD

**Issue by Debanjan-B** [w3c/webdriver#1026]
WebDriver spec needs to include the /shutdown endpoint

This is the current list of the Endpoints in the WebDriver spec-
In chapter [6. Protocol
    ](https://www.w3.org/TR/webdriver/#list-of-endpoints#h-protocol), section [6.5 List of Endpoints
      ](https://www.w3.org/TR/webdriver/#list-of-endpoints#h-list-of-endpoints):
> endpoints 

When working with with Selenium 3.5.0, geckodriver v0.18.0 & Mozilla Firefox 53.x, GeckoDriver is throwing an exception on `quit()` method. 

Bug was raised against `GeckoDriver` in the [**`geckodriver`** queue](https://github.com/mozilla/geckodriver/issues/875). 

@AutomatedTester helped me to understand that **There is no /shutdown endpoint**

	1503397488598	webdriver::server	DEBUG	-> DELETE /session/8e457516-3335-4d3b-9140-53fb52aa8b74 
	1503397488607	geckodriver::marionette	TRACE	-> 37:[0,4,"quit",{"flags":["eForceQuit"]}]
	1503397488619	Marionette	TRACE	conn0 -> [0,4,"quit",{"flags":["eForceQuit"]}]
	1503397488624	Marionette	TRACE	conn0 <- [1,4,{"error":"unknown command","message":"quit","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\n_onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
	1503397488626	geckodriver::marionette	TRACE	<- [1,4,{"error":"unknown command","message":"quit","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\n_onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
	1503397488637	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"unknown error","message":"quit","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x43ce8d - <no info>\n   3:           0x44ce14 - <no info>\n   4:           0x44944a - <no info>\n   5:           0x4203e1 - <no info>\n   6:           0x407dc7 - <no info>\n   7:           0x6d95b9 - <no info>\n   8:           0x4173a7 - <no info>\n   9:           0x6d38b3 - <no info>\n  10:      0x7fa0b421842 - BaseThreadInitThunk"}}
	Aug 22, 2017 3:54:48 PM org.openqa.selenium.remote.ErrorCodes toStatus
	INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)
	1503397488821	webdriver::server	DEBUG	-> GET /shutdown 
	1503397488825	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"unknown command","message":"GET /shutdown did not match a known command","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x43ce8d - <no info>\n   3:           0x4319fd - <no info>\n   4:           0x425ca5 - <no info>\n   5:           0x407eba - <no info>\n   6:           0x6d95b9 - <no info>\n   7:           0x417655 - <no info>\n   8:           0x6d38b3 - <no info>\n   9:      0x7fa0b421842 - BaseThreadInitThunk"}}
	Exception in thread "main" org.openqa.selenium.WebDriverException: quit

Finally, @shs96c referred the specs and made it clear that **WebDriver spec doesn't mentions about `/shutdown endpoint` so geckodriver won't implement it**

As per my understanding, `/shutdown endpoint` must be a part of the WebDriver spec and must be implemented by webdriver only. Implementing it differently though different bindings (Java / Python)  does not looks to be a great idea.

**Comment by andreastt** [comment]
We have discussed this before, and a `/shutdown` endpoint on an endpoint node does is analogous to killing the process.

The client should either realise it is talking to a WebDriver conforming remote and not send this command, or ignore the 404 response when it is talking to a conforming remote.

**Comment by Debanjan-B** [comment]
Thanks again @andreastt for all the help.

**Comment by Aparn12** [comment]
I am using FF 64.0 and selenium 3.6 .

I got below error at the time of running below code

Code


import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;


public class Login {
	
	public static void main(String []args)
	{

		System.setProperty("webdriver.gecko.driver", "C:/Java/geckodriver-v0.16.0-win64/geckodriver.exe");
		WebDriver driverobj=new FirefoxDriver();
		driverobj.get("https://illnqw1409.corp.amdocs.com:28501/idp-simulator/public/index.html ");

		
		driverobj.manage().timeouts().implicitlyWait(120, TimeUnit.SECONDS);
		
		//new Select(driverobj.findElement(By.xpath("//select[@id='userName']"))).selectByIndex(2);
		
		Select dropdown = new Select(driverobj.findElement(By.id("userName")));
		dropdown.selectByVisibleText("Asmsa1");
	}

}


Error


1507628781928	geckodriver	INFO	Listening on 127.0.0.1:11687
1507628782577	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1507628782772	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3109 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1507628783077	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\AparnaL\AppData\Local\openvr\openvrpaths.vrpath
[Child 8372] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 8372] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1507628784065	Marionette	INFO	Listening on port 51655
1507628784098	Marionette	WARN	TLS certificate errors will be ignored for this session
1507628784132	Marionette	DEBUG	Register listener.js for window 6442450945
1507628784139	addons.productaddons	WARN	Failed downloading XML, status: 0, reason: error
1507628784152	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
1507628784163	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
Oct 10, 2017 3:16:24 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1507628784224	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1507628787018	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1507628787019	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1507628790236	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://illnqw1409.corp.amdocs.com:28501/idp-simulator/public/index.html"
1507628790289	Marionette	DEBUG	Received DOM event "pageshow" for "https://illnqw1409.corp.amdocs.com:28501/idp-simulator/public/index.html"
Oct 10, 2017 3:16:30 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)
Exception in thread "main" org.openqa.selenium.WebDriverException: timeouts
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:26.402Z'
System info: host: 'APARNAL01', ip: '10.19.206.79', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\AparnaL\AppData\Local\Temp\rust_mozprofile.t9OVYWPEc80W, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=56.0, platformVersion=6.1, moz:processID=8020, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: 17d36731-a38e-4b1b-b0b6-23492e7b64e4
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:820)
	at Login.main(Login.java:25)


Can you plz let us know solutipon. I got solution from conversation as' WebDriver spec needs to include the /shutdown endpoint #1026' what should I do for this. Because. I am new selenium user

**Comment by whimboo** [comment]
@Aparn12 first, you are using a very outdated version of geckodriver. So please update to the latest one. Also please don't hijack an already closed issue. Instead please file a new issue the next time. Thanks.
