### ISSUE TITLE
Optional port for proxy host (manual mode) should default to schemes default port

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1049]
As specified in the [spec](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-host-and-optional-port):

> A host and optional port is defined as being a valid host, optionally followed by a colon and port.

It's unclear what behavior is expected when the port is not given or 0. 

Specifically for Firefox in both cases the proxy host would not be used for the given scheme. It doesn't fallback automatically to the default port of the scheme. Other browsers seem to do that.

Should we add that if the port is not in range of 1 - 65535 the scheme's default port is used?

**Comment by shs96c** [comment]
Falling outside the range of acceptable ports is an incorrect, and we I believe that this is already covered by:

> If value is not one of the valid values for that key, return an error with error code invalid argument.

Since `port` is a link to the [URL spec](https://url.spec.whatwg.org/#concept-url-port) which defines the acceptable value for a port --- falling outside of this range means, by definition, the port is not a "valid value". We could clarify this.

Handling of proxy settings is done in an implementation-specific way, so we're okay leaving the port unspecified. From step 11.3 in `New Session`:

> Take implementation-defined steps to set the user agent proxy using the extracted proxy configuration. If the defined proxy cannot be configured return error with error code session not created.

In this case, I think it might be useful to declare the default values.

**Comment by whimboo** [comment]
> In this case, I think it might be useful to declare the default values.

At least as long as those are known. For a `socks` proxy there is no default port as far as I know.
