### ISSUE TITLE
Export PDF

### ISSUE THREAD

**Issue by eduardohmg** [w3c/webdriver#1093]
Spec for printing PDF using browsers' native feature would be useful.

**Comment by eduardohmg** [comment]
Instead of waiting, I can do this by sending an http request to Chrome, like:

 `/session/:sessionId/screenshot`
for screenshot.

Can you tell me what request I have to use in order to get a PDF file on Chrome?

**Comment by jugglinmike** [comment]
A standard way to "print to PDF" would enable a number of use cases:

- web users who would like to capture a full page for use in a PDF reader
- web authors who are targeting print media
- web implementers who want to verify correctness of print-specific web platform features (e.g. [CSS Fragmentation](https://drafts.csswg.org/css-break-3/#intro))

@eduardohmg if you had other uses in mind, please let us know!

For the first two use cases, there are tools like [wkhtmltopdf](https://wkhtmltopdf.org/), and [some browsers expose command-line arguments to perform the task](https://superuser.com/questions/592974/how-to-print-to-save-as-pdf-from-a-command-line-with-chrome-or-chromium). However, because these solutions simply capture the page after it is done loading, they don't offer the kind of control that a WebDriver command would. With a WebDriver command, users could print from any state.

Chrome DevTools Protocol version 1.3 (currently designated as "Stable RC") implements [a `Page.printToPDF` method](https://chromedevtools.github.io/devtools-protocol/1-3/Page#method-printToPDF). This demonstrates that the premise is feasible and it suggests interest beyond Eduardo and me.

@AutomatedTester @andreastt can you speak to how difficult this would be to implement in Firefox? If standardized, would implementation be likely to receive priority?

@gsnedders @jgraham WPT could use this to define reftest-style tests, only comparing PDFs instead of PNGs. Does that sound realistic to you? Do you think we would need a standard, or could we get by with using proprietary binary arguments?

@fantasai Do you think we could use this feature to fully automate tests? Would it be still be useful even if the tests still had to be interpreted by a human?

**Comment by gsnedders** [comment]
@jugglinmike Yes, such a thing would be very much useful for print tests; I had some vague plan to implement roughly this in Marionette for https://github.com/web-platform-tests/wpt/issues/7760. Last I knew there was a lack of interest on the CDP side, which made it impossible to do in ChromeDriver, but obviously that has changed.

**Comment by jgraham** [comment]
> @gsnedders @jgraham WPT could use this to define reftest-style tests, only comparing PDFs instead of PNGs. Does that sound realistic to you?

Yes, I think we should try this.

In general I think the ability to generate print layouts with WebDriver seems useful and in scope. Therefore I'd support a proposal to add this feature to the standard.

**Comment by foolip** [comment]
@LukeZielinski this is a test automation capability we're lacking. Can you add this to your tracking to see if we get requests for it internally?

**Comment by jugglinmike** [comment]
Good news! gh-1468 implements "printing" to PDF

**Comment by eduardohmg** [comment]
**Another use case**: to keep equality between live shown pages and scheduled reports generated on backend.

Since there may be differences between charts and stylization on backend and frontend, one could use headless browsers to have the exacly same results.

Thank you all for bringing this up! 😄

**Comment by whimboo** [comment]
> Good news! [gh-1468](https://github.com/w3c/webdriver/pull/1468) implements "printing" to PDF

That PR got merged more than 4 years ago. So lets close this issue and individual issues can be filed for enhanced features that are still missing.
