### ISSUE TITLE
Take Element Screenshot tries to use request params, but uses HTTP verb GET

### ISSUE THREAD

**Issue by burg** [w3c/webdriver#1245]
In chapter [19. Screen Capture](https://w3c.github.io/webdriver/webdriver-spec.html#take-element-screenshot#x19-screen-capture), section [19.2 Take Element Screenshot](https://w3c.github.io/webdriver/webdriver-spec.html#take-element-screenshot#x19-2-take-element-screenshot):
> Let scroll be the result of getting the property scroll from parameters if it is not undefined. Otherwise let it be true.

However, in §6.3 Processing Model, Step 5, we only process parameters if the HTTP verb is POST. So this will always not work. I suggest changing the HTTP verb to POST, or drop the optional scrollIntoView and have clients do that some other way.

**Comment by shs96c** [comment]
Good catch. My vote is for making it a POST. I guess the alternative is to allow query parameters to be used in a GET.

**Comment by andreastt** [comment]
We can’t make a backwards-incompatible change to an endpoint now.

I believe it was Microsoft who wanted the optional `scrollIntoView` behaviour, but if that’s not used in practice, is it a controversial to propose dropping that instead?

Alternatively we need to add a _second_ POST endpoint for the same command which acts as an alias that can receive data. It is not an option to remove the GET endpoint.

**Comment by burg** [comment]
Either default for scrollIntoView is acceptable to me.

**Comment by thejohnjansen** [comment]
I think I'm being slightly misquoted. Microsoft wanted scrollIntoView to be OPTIONAL on Take Element Screenshot because I don't think Take Element Screenshot should do a scrollIntoView first. I think doing so will cause us to miss bugs. I think my example was for anchors on the page. If webdriver clicks an anchor that points to a div that is currently below the fold, the browser should scroll that div into view. If your browser (or your webpage) has a bug in it that prevents that div from scrolling into view, you'd miss that bug because WebDriver would scroll it into view for you. So, I'm OK with removing it completely and forcing webdevs to explicitly scrollIntoView before they take a screenshot if that's what they want.

**Comment by andreastt** [comment]
@thejohnjansen The argument isn’t that anyone disagrees with the _reasoning_ behind it, but that providing data with a `GET` request isn’t possible.

**Comment by InstyleVII** [comment]
In which case I'd imagine removing the body entirely and leaving the command as a GET would be fine.

**Comment by shs96c** [comment]
It's entirely possible to have GET request by allowing query parameters. For a boolean parameter this seems like a reasonable thing to do..

My concern is that either local-end bindings will always have to issue a "scroll into view" before each "take element screenshot" (which is less than ideal when dealing with cloud-hosted solutions) or there will be a number of bugs filed caused by people not expecting this behaviour.

I also agree with @thejohnjansen's reasoning for wanting this flag in the first place. I don't think it's the right thing to do to remove the functionality..

**Comment by andreastt** [comment]
Using a `GET` request with a query string is certainly possible, but there is no precedence for this elsewhere in the spec. This is not necessarily a blocker, and the benefit would be that it is backwards compatible.

My worry, and the reason for submitting #1249, is that no one actually implements this feature. This leads me to question the need for it. I think we all want the specification text to reflect the reality of the implementations and not some fantasy state, so either we need to have buy-in and commitment that drivers will implement this or my position is still that it should be yanked (and possibly re-added later when implementations emerge).

**Comment by burg** [comment]
I filed this issue because the spec is not self-consistent. I don't care on a moral level whether GET requests support a JSON payload. I just had added an early exit when non-POST requests have a payload, since it wasn't supposed to be allowed.

**Comment by burg** [comment]
The default behavior that I have implemented in Safari is to implicitly scroll into view. I don't think there is much value in adding a boolean flag that's redundant with other commands.

Can we vote to drop the 'scroll' parameter and either 1) make scroll into view the default, or 2) make not scrolling into view the default?

**Comment by andreastt** [comment]
Scrolling the element into view is what the spec also defines as the right behaviour. What we’re discussing is removing the _option to not_ scroll the element into view, essentially because it is unimplementable.

@AutomatedTester Can you weigh in on this? I think we should land https://github.com/w3c/webdriver/pull/1249 as we don’t want dead code paths or unimplemented features in the spec.

**Comment by AutomatedTester** [comment]
The scroll feature was what @thejohnjansen wanted. He wanted to scroll and to turn it off, John can you comment?
