### ISSUE TITLE
Navigate shouldn't validate URLs

### ISSUE THREAD

**Issue by InstyleVII** [w3c/webdriver#1265]
We discussed this a while back and apparently it snuck in but navigate shouldn't validate the URL handed to it. For Edge we use the top level navigation pipeline which is what a user uses when they navigate. Making navigate equivalent to window.location.href is not what users do, and if a tester wants to validate that they can validate it by executing script. We **should not** do this for navigate.

Referencing step 3 of the Navigation command, https://www.w3.org/TR/webdriver/#navigate-to

**Comment by andreastt** [comment]
It seems like this question keeps creeping up again and again.

WebDriver hooks in to HTML’s [navigation algorithm](https://html.spec.whatwg.org/#navigate), which _is not_ equivalent to setting `window.location.href`. At the point when navigation commences the URL is always valid, otherwise the algorithm would error.

As I understand it, what you are referring to are the UA specific steps taken when a user types something into the address bar and hits enter. The UA may in this case do whatever it likes because the browser chrome is not part of the web platform: it may yield a partial search as keys are entered, show you recommendations, or whatever.

The important thing to note is however that at some point the user interaction resolves to a URL that is passed to the navigation algorithm. If a user enters "w WebDriver" in the Firefox awesome bar, she is for example—by the roundtrip of some UA defined steps to figure out what that means—taken to the WebDriver Wikipedia page. In other words, the UA _translates_ the user’s request into a valid, absolute URL it can pass on to navigation.

Automation of the browser chrome element is however beyond the scope of WebDriver, simply because there are no hooks that allow us to specify that in a cross-browser way using existing web platform definitions.

**Comment by andreastt** [comment]
I believe we’ve covered this multiple times now, and based on the lack of response I’m going to close this for inactivity. Feel free to re-open if you feel otherwise.
