### ISSUE TITLE
User prompts for "beforeunload" event should not automatically be dismissed

### ISSUE THREAD

**Issue by kovalev007** [w3c/webdriver#1294]
In my opinion Section 18 contains not correct logic.

- User prompts that are spawned from beforeunload event handlers, are dismissed implicitly upon navigation or close window, regardless of the defined user prompt handler.

Example:
If we have onbeforeunload event and user try close window:
In chrome 68.0.3440.106 user should interact with promt before window will closed.
In firefox 61 user should interact with promt before window will closed.
In firefox 62beta user should interact with promt before window will closed.
In firefox 63nightly user should interact with promt before window will closed.

But in automated test with geckodriver we have different behavior.
geckodriver 0.21.0 silently set dom.disable_beforeunload to true. (in firefox 61, 62, 63)
and when test close window promt not showing and window closed.

It is different behaviour.

**Comment by kovalev007** [comment]
Additional info:
https://github.com/mozilla/geckodriver/issues/617#issuecomment-415288372
https://github.com/mozilla/geckodriver/issues/617#issuecomment-415296231
https://github.com/mozilla/geckodriver/issues/617#issuecomment-415386466

**Comment by Jarob22** [comment]
Hi - this burned us today whilst trying to write scripts to validate the appearance of a prompt on window close - is there some way we can get this addressed, please?

**Comment by zeit200** [comment]
[https://github.com/mozilla/geckodriver/issues/1563](url)
Hi, wanted to add that this behaviour blocks verifying of custom obeforeunload logic in automated tests

**Comment by Snipx** [comment]
Dear team, are there are news on this one? I agree that the specification currently blocks the use case of testing the user prompts on page reload/exit, and some of the implementing parties claim that they need to be compliant with the spec so I think the first move should be done by the spec community

**Comment by whimboo** [comment]
Note that there is ongoing work for extending WebDriver classic for WebDriver BiDi purposes on PR #1791.

**Comment by ioquatix** [comment]
I'm a bit confused about this issue.

I had the following test which no longer works in the latest chromedriver:

```
<dd><form action="cancel" method="post" onsubmit="return confirm('Are you sure you want to cancel the subscription?');"><button type="submit">Cancel Subscription</button></form></dd>
```

Test code:

```
click_button("Cancel Subscription")
accept_alert

expect(session).to have_element(css: ".subscription .status").and(
	have_attributes(text: be =~ /canceled/)
)
```

Now it appears that the form submission always fails, as `confirm` returns false. Is that expected? If so, is using BiDi the only solution? I don't really understand why this is suddenly broken.

**Comment by whimboo** [comment]
@ioquatix please note that your example is about a `confirm` prompt while this issue is about prompts as spawned by `beforeunload` events. Also if that only fails with chromedriver and not with Firefox you may want to file an issue on the chromium bug tracker instead. This repository is really for the WebDriver classic specification.

If Firefox fails as well, would you mind filing a new issue instead? Thanks!

**Comment by dcki** [comment]
> If a BiDi client is connected, the prompt will not be closed automatically

For anyone reading this, note that ChromeDriver didn't implement this until approximately version 133, and even then the options necessary are non-obvious:

```python
options.enable_bidi = True
options.unhandled_prompt_behavior = 'ignore'
```

(I'm putting this here because I found this issue long before I found the relevant [Chromium issue](https://issues.chromium.org/issues/351858989#comment30). I created [a PR](https://github.com/SeleniumHQ/seleniumhq.github.io/pull/2266) on Selenium's documentation but it seems only tangentially relevant so I think the PR may not be accepted.)
