### ISSUE TITLE
endpoint /displayed is not among list of endpoints specified in 6.5

### ISSUE THREAD

**Issue by Kreny** [w3c/webdriver#1448]
In chapter [C. Element displayedness](https://w3c.github.io/webdriver/#c-element-displayedness):
> /session/{session id}/element/{element id}/displayed.

**/displayed** endpoint still works. Based on chapter 6.5 it looks it was dropped (not int the list) but it is still being referenced in Element displayedness chapter

Please tell us what is the correct state and future of this ednpoint

**Comment by christian-bromann** [comment]
> Please tell us what is the correct state and future of this ednpoint

There is no chance to specify what displayedness means which is why this endpoint was removed moving from JSONWP to WebDriver. That said, some drivers (e.g. Chromedriver) still have this endpoint implemented as it was difficult for users to replace it. As a maintainer of WebdriverIO we already [call a substitute](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/isDisplayed.js#L69-L84) function that was copied from the Safaridriver. I don't know the state of other protocol bindings.
