### ISSUE TITLE
Any request body examples for the webdriver API?

### ISSUE THREAD

**Issue by yinzhenzhixin** [w3c/webdriver#1453]
Hi there,

I'm digging into the w3c webdriver recently. I found it's easy to send POST requests for nagativing url, locating elements and inputting text. However, is there any examples for perform actions, such as key H-e-l-l-o-w-o-r-l-d, and then key Enter. I know we have the document https://w3c.github.io/webdriver/#dfn-key-input-source, there are a lot of information without any examples, I mean the request body of the POST, could someone let me know the exact body of the my request above? Thanks in advance.

**Comment by andreastt** [comment]
Beyond the specification text I don’t know of any examples using the actions API.

You may have some luck reading the farily low-level specification conformance test suite, specifically tests under this directory:
https://github.com/web-platform-tests/wpt/tree/master/webdriver/tests/perform_actions

It may also be useful for you to look at the raw wire protocol using real-world drivers. With geckodriver you can pass `-vv` or `--log trace` to see an exact replication of what JSON bodies are passed to the session from the client.

I know this isn’t immediately useful and I would like to see more examples. Especially examples/documentation aimed at client authors (rather than driver implementors) would be welcome.

**Comment by KitoCoding** [comment]
> Hi there,
> 
> I'm digging into the w3c webdriver recently. I found it's easy to send POST requests for nagativing url, locating elements and inputting text. However, is there any examples for perform actions, such as key H-e-l-l-o-w-o-r-l-d, and then key Enter. I know we have the document https://w3c.github.io/webdriver/#dfn-key-input-source, there are a lot of information without any examples, I mean the request body of the POST, could someone let me know the exact body of the my request above? Thanks in advance.

Have you found your example? I can help C# code if you havn't

**Comment by AutomatedTester** [comment]
There are examples on how to use the API in https://github.com/seleniumhq/selenium as well the ones mentioned about
