### ISSUE TITLE
Take Element Screenshot impossible parameter "scroll"

### ISSUE THREAD

**Issue by schmorp** [w3c/webdriver#1495]
The Take Element Screenshot command currently documents a "scroll" parameter, but this parameter value is always undefined as the protocol doesn't allow parameters for this command.

**Comment by schmorp** [comment]
Also, the algorithm ignores scroll completely and says to always scroll into view, so all the references to what scroll does disagree with the remote end steps description.

**Comment by andreastt** [comment]
Thanks for reporting.

I fixed this in https://github.com/w3c/webdriver/commit/3d0755cc651ecc7427bbf081443612dd7dbec03a, but I guess because of https://github.com/w3c/webdriver/issues/1475 it was not published correctly to w3c.github.io.

Checking https://w3c.github.io/webdriver/ I can’t see that `scroll` is still there, which hopefully means we’ve finally fixed this bug.
