### ISSUE TITLE
Inappropriate browsing context checks for "Switch to Frame" and "Switch To Parent Frame"

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1539]
For both of the commands [Switch to Frame](https://w3c.github.io/webdriver/#switch-to-frame) and [Switch To Parent Frame](https://w3c.github.io/webdriver/#switch-to-parent-frame) a current browsing context check is required for the remote steps. In the case it's not open anymore the command has to be aborted with a `No Such Window` error.

There is a fundamental problem with this when the currently selected frame has been closed by some other commands like `Element Click` or some arbitrary Javascript code that remove the frame. Under such a condition it is no longer possible to switch to the parent or top-level browsing context. Only workaround is to switch back and forth between windows to reset the currently selected frame to the top-level browsing context.

In case of `Switch To Frame` we should always allow to switch to the top-level frame, and instead check if that target frame (top-level browsing context) is still open. And when switching by index or element the current check should remain.

For `Switch To Parent Frame` the parent browsing context has to be checked to be open. If it's not, an error has to be returned.

Note that from the HTML spec a user agent might [discard the nested browsing context tree at any time when a frame gets removed](https://html.spec.whatwg.org/#the-iframe-element:the-iframe-element-8). Not sure if there is something we would have to spec or if those are implementation details.

@jgraham what's your take? I'm happy to get Wdspec tests added for that, if we spec can be fixed.

**Comment by whimboo** [comment]
Actually the error to be returned if the target frame doesn't exist anymore because its browsing context is gone, should also be `No Such Frame`?

**Comment by jgraham** [comment]
So I think the problem here is that once a frame is removed, it no longer has a browsing context, so it's kind of unclear how one figures out what the correct top-level browsing context (or parent browsing context) is. I suppose we could make implementations cache the window handle for the top-level browsing context when that changes, so we could try switching to that in the case that the frame no longer exists. I don't have a strong feeling for whether the additional complexity is worthwhile; this is something that clients can also do of course. Do we already have tests for what implementations do if you switch into a frame, remove the frame, and then perform operations like `get window handle` (I'd expect that to error in this case since the current top level browsing context isn't well defined).

**Comment by whimboo** [comment]
We don't have those Wdspec tests yet, but I'm going to add them with my patch on https://bugzilla.mozilla.org/show_bug.cgi?id=1493108. So for each command we will test the behavior for a missing current browsing context, and for the top-level browsing context. These tests will be implemented based on the current WebDriver specification.

What I can actually see is that the chromedriver doesn't obey the specification here, and successfully switches to the parent and top-level frame.

**Comment by jgraham** [comment]
@JohnChen0 do you have any insight into what ChromeDriver is doing here?

**Comment by JohnChen0** [comment]
While executing most commands, ChromeDriver has code to automatically switch to the top-level browsing context if the current frame context is no longer available. It's old code that has been around since before my time, and it has caused user confusion occasionally, but it provides a way to handle current frame going away.

**Comment by whimboo** [comment]
Thanks @JohnChen0 for that information. I hope you don't mind when we go ahead with landing new webdriver tests via https://bugzilla.mozilla.org/show_bug.cgi?id=1493108, which are conformant with the current spec, but will cause test failures for Chrome then. 

We can then work out what's the best implementation here and update the tests accordingly.

**Comment by JohnChen0** [comment]
Sounds good. Thanks for the heads-up.

**Comment by whimboo** [comment]
Note that fixing the spec will take place on PR #1543.

**Comment by whimboo** [comment]
The PR has been merged.
