### ISSUE TITLE
WebElement list should perhaps be per session

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#1566]
The standard currently says we have a list of web elements per browsing context. When looking up a web element reference you take the per browsing context list for the current browsing context and look in that. If it's not found you return a `no such element` exception, and if it is found but the element isn't connected you return `stale element reference.`

It seems that implemenations typically have a per session map between web element references and elements. This can be observed by looking up a valid web element from a non-current context; in this case implementations are returning `stale element reference` when per-spec `no such element` is expected. This is the test failure for Chrome/Safari at https://wpt.fyi/results/webdriver/tests/switch_to_window/switch.py?label=master&label=experimental&aligned&q=switch.py

I doubt this is a tricky bug to fix in implementaions, but if there's a concern with compatibility here we could also change the spec to match.

cc @burg @JohnChen0

**Comment by JohnChen0** [comment]
ChromeDriver's WebElement list is actually per browsing context, not per session. The list is stored in a JavaScript object inside each browsing context, instead of in ChromeDriver memory. The [test failure](https://wpt.fyi/results/webdriver/tests/switch_to_window/switch.py?label=master&label=experimental&aligned&q=switch.py) is due to ChromeDriver returning wrong error code, and that can be fixed.

cc @k7z45

**Comment by jgraham** [comment]
Ah thanks, perfect. In that case I don't think we should change the spec here.
