### ISSUE TITLE
Merge `get a known element` into `get a known connected element` because they are mostly identical

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1662]
I just noticed that [`get a known element`](https://w3c.github.io/webdriver/#dfn-get-a-known-element) and [`get a known connected element`](https://w3c.github.io/webdriver/#dfn-get-a-known-connected-element) are mostly identical despite the fact that the latter checks for `connected` state and the former for only `is stale`. `connected` also includes a check for the active document.

Given that most commands except 4 of them use `get a known connected element` I would suggest to merge `get a known element` into it. This would also fix the case that we never actually reach step 2 from `get a known connected element` given that it calls `get known element` in step 1 and which fails with `stale element reference` in its own step 2.

Not sure why this divergence exists and maybe this was an oversight when reviewing a previous PR. But it would be good to get it fixed.

I would like to get this fixed before starting with a PR on issue #1594.

**Comment by whimboo** [comment]
@shs96c you added this extra staleness logic to `get a known element` via https://github.com/w3c/webdriver/pull/687. Do you remember why that was necessary? 

Are you ok with my proposal from above so that we can actually merge both?

**Comment by jgraham** [comment]
They are in fact exactly identical; `get a known connected element` first calls `get a known element`. If that call returns an error, which it does if the element either doesn't exist or is stale, we return that error. If the element exists and is not stale then `get a known connected element` then checks the element is connected. Since the definition of `is stale` is a superset of the definition of `is connected` this check is a no-op and therefore `get a known connected element` is identical to `get a known element`.
