### ISSUE TITLE
Should HTMLDocument nodes be serialized as web element reference?

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1687]
Right now the WebDriver specification creates a `web element reference` in [`JSON clone`](https://w3c.github.io/webdriver/#dfn-json-clone) when the `value` is of instance `Element`, which basically maps to [`Element nodes`](https://dom.spec.whatwg.org/#concept-element) in the HTML spec.

But when you check the [`Node` interface](https://dom.spec.whatwg.org/#interface-node) you can see that `Element nodes` have a type of `1` and `Document nodes` a type of `9`. That means that HTMLDocument nodes are not `Elements` for WebDriver and as such shouldn't be serialized as such.

But recently when [investigating a test failure in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1793844) I noticed that Chrome is actually passing this test and returns the `HTMLDocument` as web element reference. This is against the WebDriver specification.

The question is now if Chrome should fix that broken behavior (not sure if this could cause regressions for existing tests) or if we should allow the serialization of `HTMLDocument`. Maybe the WebDriver BiDi specification could benefit from that as well?

CC'ing @sadym-chromium and @jgraham for now, and I'll put it onto our monthly WebDriver agenda for this week.

**Comment by whimboo** [comment]
Note that `HTMLDocument` nodes do not have the full feature set as `Element nodes` have, eg. `Get Element Attribute` and others will / might not work.

**Comment by whimboo** [comment]
@sadym-chromium your feedback would be welcome. Thanks.

**Comment by sadym-chromium** [comment]
It looks like the spec tells us throwing "circular reference" exception when document is serialized, because of: 
* `document.doctype`;
* `document.firstChild.ownerDocument`;
* `document.defaultView`.

Removing the field `id` will be a breaking change, while adding new document-specific fields to serialization seems fine.

**Comment by sadym-chromium** [comment]
@whimboo sorry for the late reply, it required some research.

**Comment by whimboo** [comment]
Thank you @sadym-chromium. I'm going to land my wdspec test change on mozilla-central, which will be synced soon via https://github.com/web-platform-tests/wpt/pull/36619 so that we expect a failure and are compliant with the WebDriver specification.

If it turns out that consumers see regressions we might have to further discuss how to handle documents in detail. Until then I'll leave this issue open and will come to it once Firefox 108 is released and / or we got user feedback.

**Comment by gsnedders** [comment]
see also https://github.com/web-platform-tests/wpt/issues/30157 where I seem to have said that ad-hoc testing showed non-element node types were far from interoperable; I was sure there was some issue in this repo but I can't find it

**Comment by whimboo** [comment]
So far I haven't seen any negative feedback about this particular change. As such I would say that we close this issue as done.

**Comment by yezhizhen** [comment]
> It looks like the spec tells us throwing "circular reference" exception when document is serialized, because of:
> 
>     * `document.doctype`;
> 
>     * `document.firstChild.ownerDocument`;
> 
>     * `document.defaultView`.

I don't think this is true? Because those are not "enumerable property" for document. Only "location" is. cc @xiaochengh

Turns out Chrome/Safari do not throw error when serializing "document", only Firefox do:
https://wpt.fyi/results/webdriver/tests/classic/execute_script/node.py?label=master

https://github.com/web-platform-tests/wpt/blob/4f6743e0386708682289c48251975c36f43863f4/webdriver/tests/classic/execute_script/node.py#L78-L81
