### ISSUE TITLE
w3c wheel actions sometimes can't perform deltaX,deltaY movement

### ISSUE THREAD

**Issue by udarrr** [w3c/webdriver#1798]
Issue Description:
wheel actions sometimes can't perform movement with deltaX and deltaY as with random deltaX,deltaY value as with correct. It's been scrolling as it would be deltaX,deltaY = 0

Steps to reproduce:
here is reproducible an example https://github.com/udarrr/actionsDeltaBug

**Comment by whimboo** [comment]
I assume that in some cases different webdriver implementations throw a "not interactable" error? But that's not clear to me as of this point. Maybe you can clarify?

Further notice that the `scroll` action of a `wheel` input device is not meant to be used for scrolling a particular element into view. It will indeed work for elements that are already partially (in-view center point is visible in the current viewport) visible, but it fails on purpose otherwise.

What you probably want here is https://github.com/w3c/webdriver/issues/1005.

I'm going to close this issue as dupe for now. If I was wrong with my assumption please let me know and we can re-open.
