### ISSUE TITLE
Order of error checks in spec incompatible with proxy implementations

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#390]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29218

James Graham:

> "1. If the current browsing context is no longer open, return error with error code no such window.
> 1. Handle any user prompts, and return its value if it is an error.
> 2. Let cookie be the result of getting a property named "cookie" from the parameters argument."
> 
> This pattern doesn't work with a proxy implementation since it must read the full request before communicating with the backend that can know things like whether the browsing context is still open. Also the browsing context may close whilst the request is being read. So generally it seems better to delay these checks until after the request is fully processed.

**Comment by andreastt** [comment]
Andreas Tolfsen:
> By “proxy implementation” I’m assuming you mean “intermediary node”.
>
> You say that they need to read the full request before communicating with the backend.  I guess I don’t understand what this means, since intermediaries won’t run any of the remote end steps themselves.  They act, as you say, as proxies, or multiplexers.

**Comment by shs96c** [comment]
Assigning to @jgraham since I'm not clear if this is still valid.

**Comment by shs96c** [comment]
The steps listed are for an end node. Intermediary nodes are multiplexers. Closing this, as there's been no clarification and I don't think this is a problem.

**Comment by jgraham** [comment]
Sorry, I lost this. It's still a problem. By "proxy implementation" I mean something like geckodriver or, well or any mainstream implementation which communicates with the underlying browser through some form of IPC. In this case you don't want to check which windows exist until you have decoded the message body because doing so is racy and creates unnecessary IPC. Instead you want to fully decode the body, convert it into vendor-specific IPC calls and let the failure of those calls tell you that the current window was closed.

Concretely the difference here occurs if I arrange for the current window to be closed and then send a malformed message. Per the current spec I should get a NoSuchWindow exception, but implementations will (likely) give an InvalidArgument exception since they will process the message body first and then try to use the window.

**Comment by shs96c** [comment]
Want to put a straw man PR up, @jgraham?

**Comment by jgraham** [comment]
Fixed by 1b13c49
