### ISSUE TITLE
Dialog text is not returned if available

### ISSUE THREAD

**Issue by AutomatedTester** [w3c/webdriver#418]
In chapter [16. User Prompts](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-handle-any-user-prompts#h-user-prompts):

> In order to handle any user prompts a remote end must take the following steps: 

Selenium expects that the dialog text is returned when we hit an UnexpectedAlertPresentException

**Comment by andreastt** [comment]
What do you mean by “returned”? There’s no framework in the spec that allows us to say what should be included in an error’s message because we’ve previously agreed that this information is implementation-defined.

**Comment by AutomatedTester** [comment]
Have we agreed it was implementation defined?

**Comment by andreastt** [comment]
Yes.

Local ends should rely on the type information provided in the `error` field, as the `message` included with it could be localised (which is commonly the case on Windows) or change in time to provide better debug output.

Defining the error message string will duplicate the error type information for not obvious benefit _except_ in this particular edge case. We have decided to include more information in responses for various setters (Set Window Position and Set Window Size are examples) bu

In the cases we have decided to include additional information in responses for setters (Set Window Position and Set Window Size are examples), that data has been encoded in a known data format so that it is easy for the local end to extract it. An arbitrary error string is not a good serialisable format.

If we want to provide the alert text we need another way to encode it into the response, perhaps as a separate key in the error response:

```
{
    error: "unexpected alert",
    message: "implementation defined",
    data: {
        "text": "the text from the alert"
    }
}
```

But in the case of unexpected user prompts, I’m very doubtful if the added complexity is worth it. How often would you be calling this? I suspect it would not be a big overhead to call Get Alert Text.

I should also add that most drivers freely have chosen to include the text in the message, even if they aren’t mandated to do so. So perhaps what we can do as a compromise here is to add a note asking them to include it?

**Comment by shs96c** [comment]
As someone attempting to debug tests, having the text of the unexpected alert is a really useful tool. Because the alert is unexpected, it's not clear when to call `Get Alert Text` --- the only safe thing to do would be to wrap every call to the remote end with a try/catch block and, in the case of `unexpected alert` issue the call. This seems less than optimal.

For simplicity of local ends, it would be nice if this is in the `message` field, but if not, then using the approach suggested of returning a structured data-type would work, as would adding a new `alerttext` property to the returned error.

**Comment by andreastt** [comment]
How about adding a note suggesting to implementors that it would be nice if they included it in the error message?
