### ISSUE TITLE
Element clear command should fire input event instead of change

### ISSUE THREAD

**Issue by drjayvee** [w3c/webdriver#445]
In chapter [13. Element Interaction](https://w3c.github.io/webdriver/webdriver-spec.html#element-clear#h-element-interaction), section [13.2 Element Clear](https://w3c.github.io/webdriver/webdriver-spec.html#element-clear#h-element-clear)::
> 7.2. Fire a change event. 

Since the element is not blurred, no `change` event should be fired. Instead, an `input` event should fire. This change would make events consistent with those fired when an actual user clears an input element.

See https://github.com/SeleniumHQ/selenium/issues/1841

**Comment by shs96c** [comment]
The original selenium code that this function is derived from fires a "change" event. An "input" event does seem reasonable to fire. Wondering whether we should blur the element too and therefore cause the "change" event to fire if necessary.

**Comment by drjayvee** [comment]
I'd actually prefer `clear` to _not_ blur.

I ran into this problem while writing test for code that registers listeners for `input` events (see [this issue in selenium](https://github.com/SeleniumHQ/selenium/issues/1841)). To trigger that listener (and _only_ that listener), I have to resort to nasty workarounds such as `sendKeys("Control-a, backspace")`.

Blur can be achieved by sending the tab character (among other means). Maybe a `blur` command would be useful addition to make this more explicit. But in the context of this issue, the point is that there's already a good way of triggering `blur` events. The same is not true for `input` events.

**Comment by shs96c** [comment]
I've made "Element Clear" mirror the behaviour of "Element Send Keys", which does a blur after appending text, and therefore you'd expect to see the change event. The proposed wording, however, also causes the input event to fire.

These high-level "do what I mean" APIs are designed for the common case that most users have. Typically with text entry, the desire is to have someone fill out a form field and then move on to the next one, causing any relevant handlers to be used, so I think this is expected behaviour. 

In the case of testing a single input event, might a normal JS test be more appropriate? Without more context into your goals, I'm not sure how to respond best,

**Comment by drjayvee** [comment]
> I've made "Element Clear" mirror the behaviour of "Element Send Keys", which does a blur after appending text, and therefore you'd expect to see the change event.
I don't think that's correct, actually.

[The spec](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-element-send-keys) does not mention the `change` event (only `keyDown`, `keyPress` and `keyUp`).

I just tested this (Selenium 2.53.1 with latest Chrome on Windows), and "send keys" does _not_ cause `blur`. (It does, by the way, cause `input`!) I'm pretty sure that's how it works in other browsers (and versions of selenium) because I have plenty of tests that explicitly send the tab character to cause the blur.

I agree that Element Clear should mirror Element Send Keys. Since the latter does _not_ cause `blur`, neither should the former.

Did I perhaps misunderstand what you meant?

>These high-level "do what I mean" APIs are designed for the common case that most users have. Typically with text entry, the desire is to have someone fill out a form field and then move on to the next one, causing any relevant handlers to be used, so I think this is expected behaviour.
I'm not sure I understand. Are you saying that users expect the next input to get focus after Element Clear?

Consider a test where we send keys to two inputs and then click submit button. In this case, the events are:
```
input1.sendKeys("hello");   // focus input1
input2.sendKeys("world");   // blur input1, focus input2
submit.click();             // blur input2, focus submit
```
In this sequence, we still get all the expected `blur` (and `focus`) events. It's just that `input1`'s `blur` fires only after `input2.sendKeys()` (_not_ immediately after `input1.sendKeys()`). To many users, this order probably doesn't make any difference. Therefore, implementing my proposed changes would break few tests.

> In the case of testing a single input event, might a normal JS test be more appropriate? Without more context into your goals, I'm not sure how to respond best,

Consider this functionality that we want to test:
```javascript
submit.disabled = true;  // start disabled

// disable submit button if input1 is empty
input1.addEventListener("input", function () {
  submit.disabled = input1.value === "";
});
```
Our test would look like this:
```javascript
assertFalse(submit.isEnabled());

input1.sendKeys("hello");
assertTrue(submit.isEnabled());

input1.clear();
assertFalse(submit.isEnabled());
```
The last assertion will fail, because `clear` does not cause `input`.

By the way, we don't do any "normal" js tests but instead do all javascript testing in Selenium. Makes it easier because we don't need to create and maintain fixtures, and we also gather all code coverage data in one go as well.

**Comment by shs96c** [comment]
The spec for "Element Click" is currently woefully incomplete, but it should mirror the existing Selenium WebDriver behaviour. There's a pure JS implementation of this that starts at "[WebElement.clickElement](https://github.com/SeleniumHQ/selenium/blob/master/javascript/firefox-driver/js/wrappedElement.js#L63)", and ends up in "[bot.action.click](https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/action.js#L266)". Interestingly, this _doesn't_ fire the blur. Also interestingly, the Selenium tests for the correct behaviour of clear states that the [change event is meant to fire](https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/CorrectEventFiringTest.java#L272) when using it, and this is what happens in the [atoms](https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/action.js#L93) so it seems as if the two cases have different expected behaviour in Selenium (you'd think I'd remember writing those tests, no?)

> I'm not sure I understand. Are you saying that users expect the next input to get focus after Element Clear?

They're not expecting the next input to get focus, they're expecting the current input to lose focus.

If you read the spec as it's currently worded, you'll see that clear does fire both an `input` if the value changes, and any events that would be fired during the unfocusing steps.

**Comment by drjayvee** [comment]
So there are a few inconsistencies in behavior? Outrageous! 😄 
Anyway, let's stick to `clear` and `sendKeys` for now, okay?

>> Are you saying that users expect the next input to get focus after Element Clear?

> They're not expecting the next input to get focus, they're expecting the current input to lose focus.

Well I for one didn't expect that, and [I'm not alone](https://github.com/SeleniumHQ/selenium/issues/1841). Of course I don't know which expectation is more reasonable or common. Maybe you could ask other contributors to weigh in?

Speaking for myself though, I would assume clear is a way to simulate a user clearing an input using Control-a, backspace or selecting with mouse and cutting, among other methods. If I do exactly that in a browser, the input hasn't yet lost focus, so there should be no `blur` and `change` events.

> If you read the spec as it's currently worded, you'll see that clear does fire both an input if the value changes, and any events that would be fired during the unfocusing steps.

I'm quite certain that the "Run the unfocusing steps for the element" was not present in the spec when I filed this issue. Is that correct?

This issue was originally about the `input` event. That has been added, which I'm very happy about!

What we're arguing about now is whether or not the input should lose focus and therefore fire `blur` and `change` events. If I understand correctly, you're arguing that "blur after clear" is more intuitive (i.e. most users will expect this behavior).

I would argue that it's a pity that there's no nice way to implement "clear without blur" (`sendKeys("Control-a, backspace")` and other hacks are nasty and probably break in mobile browsers), and that most users won't notice the difference between our approaches since most commands (issued after clear) will cause the blur anyway (see my example).

If I understand correctly, you would propose that both `clear` and `sendKeys` should each cause the following events (among others): `focus`, `input`, `blur`, `change`. Therefore, if the system under test has different event handlers for `input` and `change`, it's not possible to test these individually (again, without resorting to nasty workarounds).

**Comment by shs96c** [comment]
The [javadocs for "clear"](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebElement.html#clear--) are unambiguous that this isn't exactly emulating user behaviour:

`Note that the events fired by this event may not be as you'd expect. In particular, we don't fire any keyboard or mouse events.`

It was designed to allow a test to quickly reset the state of an input element or contentEditable without much mucking around, and the events it fires are based on a long history of bug reports and people expecting certain events to fire ("`onchange`" being the most notable)

> I'm quite certain that the "Run the unfocusing steps for the element" was not present in the spec when I filed this issue. Is that correct?

When you filed, that is correct. That's why I pointed you back at the spec :)

We're not really arguing. For the common use case `clear` was designed for, the behaviour given in the spec is great. For "clear without blur", I'd suggest measuring the length of the current text value and using "send keys" with that number of backspace operations. More importantly, this preserves the existing Selenium WebDriver behaviour which is what will allow existing tests to continue to function as expected. This also means that we'll retain the existing Selenium WebDriver behaviour with `Element Send Keys`

**Comment by twalpole** [comment]
I'd just like to point out that the example mentioned earlier `sendKeys("Control-a, backspace")` isn't actually possible anymore since the sendKeys spec removed the ability to release modifier keys part way through.

**Comment by shs96c** [comment]
I've opened #553 to address resetting keyboard input state midway through sendKeys. I think the `Element Clear` command is now pretty well fleshed out. Please raise new bugs to change its functionality.

**Comment by jedwards1211** [comment]
@shs96c if element clear isn't intended to be an emulation of user behavior, then should we add another command to the WebDriver spec that is an emulation of user behavior?
The problem is to authors of a lot of companion libraries element clear seems ideal to use for changing the value of an input, so they end up using it, and only those of that run into problems and dig into why they're happening figure out that element clear actually isn't good for the common use case.  #1630

**Comment by whimboo** [comment]
@jedwards1211 this issue is closed. Please lets continue in #1630.
