### ISSUE TITLE
Need mechanism to restore window to original size

### ISSUE THREAD

**Issue by shs96c** [w3c/webdriver#558]
Many windowing systems allow a window to be minimized, maximized, or made full screen. They also allow the inverse of that operation: returning the window to the size originally defined by the user or OS.

We now have commands for each of these operations, other than restoring a window to its original size. We could simulate that on the local end by storing the original window size before calling any window-resizing operations, and simply calling `Set Window Rect`, but symmetry suggests adding a separate command.

Should we not do this, then we should make clear that a call to `Set Window Rect` should (at the very least) un-minimize, and un-fullscreen the window.

**Comment by andreastt** [comment]
Usually resetting the window to the original size after maximising it is done by doing the same operation again. I.e. under most X windowing systems and macOS you maximise the window and return it to its original size by performing the same operation.

We could approach this by encoding the original window position as session state in the _Maximize Window_ command, or we could be hand-wavy and say something along the lines of “do the default thing the system does”, which I think is implied already.

The problem is that we don’t know the details of the windowing system, but we could point it out in some fluffy way what the current realities are.

> [W]e should make clear that a call to Set Window Rect should (at the very least) un-minimize, and un-fullscreen the window.

Filed https://github.com/w3c/webdriver/issues/562.

**Comment by shs96c** [comment]
Having the opposite of the command happen when you invoke it again is confusing, though I can see the logic.

I'm happy to just delegate down to the underlying windowing system and have that handle restoring window state. I think if we fix #562 then we can close this issue.

**Comment by andreastt** [comment]
I tend to agree it is confusing, considering the commands’ intention is expressly stated. I don’t think I have any great ideas, although I suppose you could tell from _Maximize Window_’s return value whether the window was maximised or returned to its original state.

**Comment by shs96c** [comment]
Closing this issue, since I think #562 gives us reasonable behaviour without requiring a new end-point.
