### ISSUE TITLE
Remove paragraph about drivers not supporting TLS certificates management

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#633]
In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-user-prompt-handler#h-capabilities), section [7.3 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-user-prompt-handler#h-processing-capabilities):
> If capability value is true and the endpoint node does not support insecure TLS certificates, return null.

As far as I’m aware, it is not an option for endpoint nodes to _not_ support insecure TLS certificate handling. This entire paragraph under capabilities processing can be removed.

**Comment by shs96c** [comment]
I think Apple raised concerns about this at the Lisbon F2F.

**Comment by AutomatedTester** [comment]
@burg wish to comment on this?

**Comment by burg** [comment]
Re: the default value of this capability:
I pushed against making this the default at Lisbon F2F because being insecure is the wrong default, whether or not Apple plans to support it.


Re: whether it would ever be off:
Given the usage of system-level security, network, and proxy settings, it is unlikely that this can functionality be implemented on all Apple platforms satisfactorily. We have not seen many user requests for this functionality, though the priority could be upgraded if user requests increase. I'm not aware that it is blocking any major users or cloud providers. I would love to hear evidence to the contrary from users if I am mistaken.

**Comment by shs96c** [comment]
The Selenium project used to get plenty of requests for being able to test pages with an invalid certificate mainly because plenty of orgs aren't aware of (or don't prioritise) setting up their QA/UAT environments with a proper cert. It's important to be able to turn this off for many users.

**Comment by shs96c** [comment]
Seems like the best thing to do is to edit the spec so that if someone asks to accept insecure certs on a platform that doesn't allow this we return an `invalid argument` error.
