### ISSUE TITLE
Proposal: drop platformVersion

### ISSUE THREAD

**Issue by shs96c** [w3c/webdriver#741]
In the Capabilities section, `platformVersion` is hard to define clearly. Current "Selenium As A Service" vendors ignore the field in favour of their own mechanisms:

https://www.browserstack.com/automate/java#configure-capabilities
https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/

Rather than attempt to specify this in the spec, it's probably best to remove this field entirely.

**Comment by jlipps** [comment]
Sorry I missed this while it was open. Sauce does in fact use the `platformVersion` capability for all its Appium tests. This is because Appium endeavors to use the new spec (`platformName`, `platformVersion`, `deviceName`, etc...). As we discussed at the mobile spec summit some years ago, it's necessary to have a few different dimensions to specify the thing to automate when you're talking about mobile.

Sauce's "traditional", se2-based capability structure is legacy and will be upgraded to support the new capabilities at some point, even if support for the legacy scheme lives on for some time.

I think `platformVersion` is immensely important and would lobby to have it reinstated. Imagine a scenario, not too far off, where you want to specify which version of Chrome to automate on an Android device. You'd need something like this:

```
{
  "platformName": "Android",
  "platformVersion": "7.1",
  "deviceName": "Nexus 6",
  "browserName": "Chrome",
  "version": "44"
}
```

It seems like a globally useful concept, not something specific to one or another vendor. Rather than have different webdriver-based implementations and cloud services attempt to solve this problem in different ways, I'd rather see us all agree on something!

Thoughts? Perhaps I'm unaware of some of the context which makes this capability problematic, and would love to be a part of that discussion.

**Comment by shs96c** [comment]
It's a useful concept that implemented in many different ways. Some folks use the major version of the OS's user-facing name (Windows 10 -> "10", OS X -> "Sierra"), whilst others use the underlying OS version (OS X -> "10.12.3") In some cases, it's meaningless (Linux -> ???) As part of the spec, we'd need to mandate what this field meant, and provide a meaningful list of variants seen in the wild that would remain relevant. Looking at the usage of the browser-based implementations, none actually used the platformVersion in a significant way (BrowserStack don't use, Sauce doesn't use it, Grid thinks it does, but ultimately only looks at `platformName`, geckodriver, Windows WebDriver, and the selenium server all ignore it)

I agree it's a useful concept, but there's no agreed way to clearly define what it is that doesn't also leave the door open to a lack of interoperability (cf: Sauce and BrowserStack both have a different idea of what to put in fields with the same kind of meaning) Given the amount of time left in the charter for this WG, there are better ways for us to spend our efforts than attempting to "nail jelly to the wall" with attempting this definition.

**If you'd like to put forward a PR that reinstates it and we can get agreement on, I'll happily consider adding to the spec.**

`platformName` suffers from the same problem, but at least the listed platforms have been stable for at least 15 years and have commonly understood names.

**Comment by jlipps** [comment]
Thanks for the context @shs96c! For the purposes of nailing down the current spec, your proposal makes sense to me. I was worried that this lack of `platformVersion` would live on forever, even into any subsequent mobile specs, which is where I find it has the most traction anyhow.

All that to say, I think there should be a follow-on conversation about `platformVersion` when the spec is ready to consider mobiley things, and take the opportunity to clarify what kind of usage makes the most sense then, potentially making it "retroactively" relevant to browsers. (Correct me if I'm wrong, but adding a capability to a spec later on down the road which adds additional meaning is probably easier than removing one once it's set in stone?)

**Comment by titusfortner** [comment]
So if the spec says that "platformName" should be `linux`, `mac`, or `windows`, how are we supposed to distinguish between Windows 10 & Windows 8, etc? I'm not sure why there's a concern about who is already using it since no one has fully implemented the existing specification, yet. :)

Admittedly I don't really understand the spec, because the way I read it, unmatched desired capabilities (like browserVersion) are supposed to return "null" instead of raising an error which is apparently not the case. If it were more relaxed about matching, then getting the exact correct platformVersion of "10.2.4" vs "10" wouldn't matter as much and could be addressed on a per case basis by the server/hub/SeAAS provider.

**Comment by shs96c** [comment]
@titusfortner The spec is mostly derived from existing Selenium usage. In that usage `platformVersion` is effectively unused, as pointed out above. The various cloud providers are not using the capability name, so it's clearly not providing value. It's used by appium, but the mobile parts of this spec have been pushed to Level 2, so aren't a concern right now. `platformName` _is_ used, and the values given in the spec have been stable for a long time (and, you'll notice, don't include the mobile platform names, though the list is given as "non-exhaustive")

There's nothing in the spec that says that additional capabilities can't be added (indeed, a mechanism for doing so is in [section 6.7](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-extension-capabilities), and I'd expect the mobile JSON Wire Protocol Spec to clearly define this capability, it's meaning, and how to process it, ready for Level 2 of this spec.
