### ISSUE TITLE
Consider removing opacity check for element interactability

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#746]
Currently we have the following step in the spec for element intractability which seems to be obsolete given that we already do a hit test:

> An element is considered transparent if its opacity style property has the computed value of "1". 

Also even with an opacity value of 0 < 1 elements can be intractable, and having this limitation might stop users from actually doing real tests.

As @AutomatedTester mentioned in our meeting yesterday we might want to get it removed.

**Comment by andreastt** [comment]
I’d like to voice my support for this. The opacity test on elements is a leftover from the old visibility checks. Since we now do hit-testing to determine if the element is _interactable_, it seems weird to not deem an element that may be clicked by a user and which would generate DOM events non-interactable.

I believe some of the original concerns have been, at least partially, addressed by the element click intercepted error that was recently added, which checks that the element is the first element on the paint-tree array.
