### ISSUE TITLE
Format string literals as <code>"foo"</code>

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#785]
The current style with the quotes outside the `<code>` is rather confusing because it isn't clear if the thing inside the quotes is a literal or some other kind of argument like an identifier. In HTML the style is to use `"<code>SecurityError</code>"` for identifiers and `the literal string "<code>%s</code>"` for literals. But since we have so many more literals than most specifications, I think using `<code>"%s"</code>` is more concise.

**Comment by andreastt** [comment]
I find `<code>"foo"</code>` more confusing because it isn’t clear if the quote marks are part of the string or not: with `"<code>foo</code>"` there is no doubt that this is a string type with the value `foo`.

When we refer to field names in JSON we often omit the quote marks altogether, which I also think is fine where it is unequivocally clear from the context. Perhaps it would be acceptable to do this also in other contexts.

**Comment by jgraham** [comment]
Per the style of other specs `"<code>foo</code>"` isn't unambiguous because `foo` can be an identifier rather than a string.

**Comment by jgraham** [comment]
Although DOM matches your style so… I think the conclusion is that nothing you choose here is either consistent or confusing.
