### ISSUE TITLE
HTTP-Level DOS mitigation

### ISSUE THREAD

**Issue by jugglinmike** [w3c/webdriver#872]
[The Interface section](https://www.w3.org/TR/webdriver/#interface) defines a `navigator.webdriver` property, giving the following motivation:

> The webdriver IDL attribute of the Navigator interface must return the value
> of the webdriver-active flag, which is initially false.
>
> This property allows websites to determine that the user agent is under
> control by WebDriver, and can be used to help mitigate denial-of-service
> attacks. 

This is good for the JavaScript execution context, but I'm wondering if the same kind of feature could promote safety when it comes to HTTP requests. If this specification extended [Fetch](https://fetch.spec.whatwg.org/) such that all requests included some special header (e.g. `WebDriver: true`), it would be easier for networks to shunt requests from automated browsers.

**Comment by andreastt** [comment]
Related discussion in https://discourse.wicg.io/t/proposal-to-advertise-ua-automation/1962, where I wrote

> Let’s be clear that the security model here is different to that of browser content. You can modify any user agent to disable security measures if you have access to the browser binary, not limited to whether a WebDriver-controlled browser sends a specific header.
>
> I can see a potential use case that websites want to prevent remote controlled browsers from crawling their website, but giving them a header is comparable to UA string sniffing, which websites already do to gate certain browsers from accessing content. Dedicated users spoof the UA string to circumvent this, both for pleasure and automation.
>
> Giving a UA under automation a header would ensure the UA string remained unchanged, potentially letting websites trigger an ‘automation mode setting’ but still trigger the UA sniffing behaviour.
>
> In any case, I’m not sure this is desirable to give websites another mechanism for sniffing the client, potentially fragmenting the web further. On the other side, because it’s impossible to prevent a user modifying the UA, maybe an automation header would be useful if only for convenience.
>
> However, the use cases listed here so far are not convincing: If sending automation tools could avoid CAPTCHAs and ads by sending a header, what would prevent users from modifying their own browsers to do the same? I think the only safe option for triggering ‘test mode’ behaviour on your website is to spin it up an instrumented version in a controlled test environment.

**Comment by jugglinmike** [comment]
Thanks for that! The threat I had in mind involves situations where the
attacker does not necessarily control the browser binary--possibly in
distributed denial of service attacks. WebDriver could be used in orchestrating
many browsers to flood a target network with spurious traffic. This probably
goes without saying, but I am no security researcher. My understanding of the
threat model is pretty hazy, so I'd be satisfied with the opinion of a spec
editor on this topic.

**Comment by andreastt** [comment]
Yes, I agree you line out kind of the reverse of the attack vector that is being outlined by the original poster of that thread on WICG.

You make a good point that WebDriver is especially prone to be used in a distributed denial of service attack, and that current measures make it hard for those at the receiving end of this to distinguish between real users and automated bots flooding them with traffic. I think we should revisit this.

**Comment by shs96c** [comment]
This is essentially a discussion about the evil bit
<https://www.ietf.org/rfc/rfc3514.txt>. Folks already have access to
selenium and can already launch these kinds of attacks. They already do, in
some cases, but it's easier to use other tooling (such as curl, ab, or
wget) instead. I've worked with at least one company to help develop these
mechanisms, and I'd be staggered if other companies didn't have the same
thing in place too.

In order to use webdriver for DOS, the attacker must be able to start their
own automated browser instance, which is non-trivial in all cases I'm aware
of and often means that local machine has been thoroughly compromised (to
the point where it's possible to run a lightweight proxy that strips any
header)

More beneficial would be for each implementor to supply a public document
describing the fingerprint left by their chosen automation mechanism so
that folks running sites have the option of implementing strategies to
mitigate risks against those. As an example, a key feature of Selenium's
original FirefoxDriver was to register a listener at the top of the
document to listen for commands and responses from pages being tested.
Because the driver couldn't function without this, this gave site owners an
impossible to avoid fingerprint to check for automation.

To be honest, the webdriver flag on navigator is really only a politeness
measure, and could be removed from the spec following the same reasoning.

Cheers,

Simon

**Comment by jugglinmike** [comment]
> This is essentially a discussion about the evil bit
> <https://www.ietf.org/rfc/rfc3514.txt>. [...]  To be honest, the webdriver
> flag on navigator is really only a politeness measure, and could be removed
> from the spec following the same reasoning.

I wasn't aware of the evil bit; that's pretty interesting! At first glance, I
was tempted to suggest that we go the other way: err on the side of
"politeness" and specify the use of the evil bit in WebDriver. But on closer
reading, that would most certainly interfere with legitimate communication
during internal testing, so it wouldn't be appropriate here.

> In order to use webdriver for DOS, the attacker must be able to start their
> own automated browser instance, which is non-trivial in all cases I'm aware
> of and often means that local machine has been thoroughly compromised (to the
> point where it's possible to run a lightweight proxy that strips any header)

This is exactly the kind of perspective I was lacking. Thanks for providing it!
I'm taking off the "web security advisor" hat. It was too big for me, anyway.

**Comment by shs96c** [comment]
It's a great thing to bring up --- this spec has the potential to cause some interesting challenges that other specs don't often have to deal with. Thanks for reminding us of that! :)

**Comment by drzraf** [comment]
9 years later. Time to reconsider. `navigator.webdriver: true` is now just a synonym of being unable to browse half the web. Anti-bot has never been as pervasive as today, impacting everyone in our daily life, real humans. Meanwhile bots can still find a way to live as freely as before.
Cloudflare/Google & co are blocking `webdriver: true` almost systematically which alone makes this flag counter-productive.

There are dozens of anecdotes where legitimate users having to rely on browser automation ended up blocked from accessing services, or even kept from downloading their own content hosted behind some bot-detector.

**bot detection == user-control** (if there is only one fundamental fact to understand, it's this one. And that's why bot-detection has been overplayed by some large network actors)

In the interest of the humans, this `webdriver` property (which effectively increased web fragmentation), must be made user-configurable (or deprecated) due to the lengthy and reiterated abuses from corporations using it to control users, behind the pretext of blocking bots.

`navigator.webdriver: true` should have been considered as a **hint** in case operator's server actually received an unsustainable amount of traffic ? Now, just make a simple GET on a public/cached resource from an webdriver-enabled browser from a home connection : get endless captcha.

With this property, w3c did its share of goodwill aiming at a _polite web_ for a time, at the prejudice of users freedom.
This compliance has been absurdly abused (by corporations more than scrappers), and its time to stop mandating the browsers to advertise any sign of automation.
