### ISSUE TITLE
getScreenshotAs() function can't get full website screenshot

### ISSUE THREAD

**Issue by AnneGuo** [w3c/webdriver#981]
OS:
Windows7
Selenium Version:
Selenium 2.53
Browser:
Firefox 45.3.0 ESR

I had used GeckoDriver to get screenshot ,but the screenshot is not the full website screenshot.But I want to scroll to get full website screenshot,so I choose selenium 2.53 and firefox 45.3.0 ESR.I got the full website screen ,but the website is so long,a part of the screenshot's bottom can't be take.I found the Maximum length may be 8200px.Is there any definition of getScreenshotAs() function to see the Maximum length of screenshot?Or is there any method to set up the Maximum length of screenshot?

**Comment by andreastt** [comment]
This repository covers the WebDriver specification.

**Comment by arvindpdmn** [comment]
I request this issue be reopened. I think it would be nice to update the specs to allow WebDriver to take screenshot of the entire page. This is in addition to current specs that allows screenshot of viewport.

This issue was raised in Chrome, but they said that the specs should be updated first: https://github.com/SeleniumHQ/selenium/issues/4300

For testing the design and visual layout of long pages, this is really a useful feature. It's supported by Mozilla geckodriver, where we can do the following (an example in Python):

```
def save_screenshot(name, elem=None):
    if elem is None:
        driver.save_screenshot(name)
    else:
        elem.screenshot(name)


elem = driver.find_element_by_css_selector("body#main")
name = "page.png"
save_screenshot(name, elem)
```

**Comment by andreastt** [comment]
It is problematic to take screenshots of full documents because it inevitably involves scrolling and “stitching” together multiple screenshots in browsers such as Chrome. Because a scroll might invoke changes introducing new DOM content (example being a never ending Twitter feed), it is impractical for WebDriver to support his as an API.

Firefox/Gecko _does_ support dumping the framebuffer of the full document, without invoking updates, and it is a long-term intention of ours to expose this through a so-called [extension command](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-extension-commands).

**Comment by tpangburn** [comment]
I recently updated to using the new webdriver i.e. geckodriver 0.21.0 with firefox 61.0.1. I use to use the cntl '-' to zoom out so I could get the whole screen shot. Then I found out they got rid of being able to do browser specific send keys. So essentially my whole testing environment is broken as it stands because there seems to be no way to get a full screen shot. I tried to use the element screenshot to get the whole screen and it isn't working for me so far. So I would also like to see a way to do a full screenshot added. For now I may have to downgrade back to my old environment as this really kills my whole testing needs.

**Comment by tpangburn** [comment]
Because don't know about a full document screenshot API or how to use it. Do you know specifically how I would implement that? I can't claim I am a super user of selenium/python I just know some of the basics.

**Comment by tpangburn** [comment]
I'v searched all over the place I still can't seem to find anything that would show me how to get a full-screenshot using the geckodriver API. Would anyone have maybe even a link that would be useful for doing it in python? Am I missing something obvious here?

**Comment by whimboo** [comment]
While geckodriver exposes this flag, the Python binding might not make use of it. As such you won't be able to use it.

**Comment by tpangburn** [comment]
Oh OK.. I forgot to come back and check this thread. So would you or anyone know if there are any plans on adding the binding capability to python in the future? Just Curious.

**Comment by andreastt** [comment]
That is off-topic for this discussion.
